apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260606-135112-8m3ryvl3uyqw-service
spec:
  selector:
    app: enterprise-system-20260606-135112-8m3ryvl3uyqw
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
